from __future__ import annotations

import datetime as dt

INTERVAL_MINUTES = 5
SLEEP_TIME = dt.time(20, 45)

WEEKDAY_START_HOUR = 16
WEEKDAY_START_MINUTE = 15
WEEKEND_START_HOUR = 9

DEFAULT_DURATION = 30
MIN_DURATION = 5
